name: GitHub Actions Demo
inputs:
  ports:
    description: The server port to listen on.
    default: "1521"
    required: false

runs:
  using: "composite"
  steps:
#      - name: Set up Docker
#        uses: docker/setup-docker-action@v4
#
#      - name: Run Docker command
#        run: docker --version
    - name: Start Oracle container
      run: |
        $values = "1521", "1522"
        foreach ($P in $values) {
         Write-Host "Processing value $P"
        }
      shell: pwsh

    - name: Start Oracle container 3
      run: |
        echo 111111
        echo ${{inputs.ports}}
        $values = '${{ inputs.ports }}' -split ' '
        echo $values
        foreach ($P in $values) {
          Write-Host "Processing value $P"
        }
      shell: pwsh
