name: GitHub Actions Demo
inputs:
  ports:
    description: The server port to listen on.
    default: "1521"
    required: false

runs:
  using: "composite"
  steps:
#      - name: Set up Docker
#        uses: docker/setup-docker-action@v4
#
    - name: Run Docker command
      run: docker --version
      shell: pwsh

    - name: Start Oracle container
      run: |
        $values = "1521", "1522"
        foreach ($P in $values) {
         Write-Host "Processing value $P"
        }
      shell: pwsh

    - name: Start Oracle container 3
      run: |
        echo ${{inputs.ports}}
        $values = if ('${{inputs.ports}}' -match ' ') {'${{inputs.ports}}' -split ' ' } else { @('${{inputs.ports}}') }
        foreach ($P in $values) {
          Write-Host "Processing value $P"
          Write-Host "docker run -d --name ${{ inputs.version }}-$P -p $P:1521 container-registry.oracle.com/database/free:23.5.0.0-lite"
          
        }
      shell: pwsh
