name: Windows Demo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  job1:
    name: this is job1
    runs-on: windows-latest
    steps:
      - name: Set up Docker
        uses: cpunion/setup-docker@v1

      - name: Run Docker commands
        run: |
          docker --version
          docker info