# Output Demo
name: Windows Demo
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    # Expose step outputs as job outputs
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      output3: ${{ steps.step3.outputs.test }}
    steps:
      - id: step1
        run: |
          echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: |
          echo "test=world" >> "$GITHUB_OUTPUT"
      - if: runner.os == 'Windows'
        id: step3
        run: |
          echo "test=leo" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}} ${{needs.job1.outputs.output3}}
          echo