name: GitHub Actions Demo
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    name: this is job1
    runs-on: windows-latest
    steps:
      - name: Install Docker
        run: |
          choco install docker-desktop
          Start-Process 'C:\Program Files\Docker\Docker\Docker Desktop.exe' -ArgumentList '--install' -Wait

      - name: Run Docker command
        run: docker --version

      - name: Pull Docker image
        run: |
          docker --version
          docker pull registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c
