# Action Cache docker container Demo
name: Docker Cache image Demo
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
jobs:
  job1:
    name: cache docker container
    runs-on: ubuntu-latest
    steps:
      - name: Restore oracle Cache
        id: restore
        uses: actions/cache/restore@v3
        with:
          path: ~/docker/image
          key: Linux-nginx-container

      - name: docker pull image
        if: steps.restore.outputs.cache-hit != 'true'
        run: |
          docker pull nginx
          mkdir -p ~/docker/image
          docker run --name nginx0 -d nginx
          docker commit nginx0 nginx:v1
          docker save -o ~/docker/image/nginx.tar nginx:v1
          docker stop nginx0
          docker rm nginx0
      - name: docker run image
        run: |
          echo $(ls ~/docker/image)
          docker load -i ~/docker/image/nginx.tar
          docker run --name nginx1 -d nginx

      - name: Save oracle Cache
        if: steps.restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/docker/image
          key: Linux-nginx-container