# Workflow: workflow demo 入口程序
name: GitHub Actions Demo
#on:
#  push:
#    branches: [ "main" ]

jobs:
  setup-oracle23:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sysctl machdep.cpu.brand_string
          sysctl hw.physicalcpu
          sysctl hw.logicalcpu
          sysctl hw.memsize
          brew update 
          brew install colima docker qemu

      - name: Start Colima
        run: |
          colima start --arch x86_64 --vm-type=vz --vz-rosetta --mount-type=virtiofs --memory 6 --cpu 2

      - name: Pull Oracle Database 23 Free Image
        run: |
          docker pull container-registry.oracle.com/database/free:23.5.0.0-lite

      - name: Run Oracle Database Container
        run: |
          docker run -d \
            --name oracle23 \
            -p 1521:1521 \
            -p 5500:5500 \
            -e ORACLE_PDB=ORCLPDB \
            -e ORACLE_PWD=Oracle123 \
            container-registry.oracle.com/database/free:23.5.0.0-lite

      - name: Verify Oracle Database is running
        id: oracleContainer
        shell: bash
        run: |
            docker ps
            sleep 10
            while true; do
              log_output=$(docker logs oracle23 2>&1 | grep -i "DATABASE IS READY TO USE" || true)
              if [ -z "$log_output" ]; then
                echo "'XDB initialized' not found in the logs, retrying in 100 seconds..."
                docker logs --tail 10 oracle23
                sleep 30
              else
                echo "'XDB initialized.' found in the logs, continuing."
                break
              fi
            done
