# Action Cache Demo
name: Actions Cache Demo
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
jobs:
  job1:
    name: cache jars
    runs-on: ubuntu-latest
    steps:
      - name: Restore oracle Cache
        id: restore
        uses: actions/cache/restore@v3
        with:
          path: ~/.m2
          key: Linux-maven-ojdbc8

      - name: Download and Install Oracle JDBC Driver
        if: steps.restore.outputs.cache-hit != 'true'
        shell: bash
        run: |
          wget https://download.oracle.com/otn-pub/otn_software/jdbc/236/ojdbc8.jar
          mvn install:install-file \
          -DgroupId=com.oracle \
          -DartifactId=ojdbc8 \
          -Dversion=19.3.0.0 \
          -Dpackaging=jar \
          -Dfile=ojdbc8.jar
#          echo $(ls -a ~)
#          echo $(ls -a ~/.docker)
      - name: Save oracle Cache
        if: steps.restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/.m2
          key: Linux-maven-ojdbc8

