name: Use Oracle Service

on:
  push:
    branches: [ "main" ]
jobs:
  use-oracle-service:
    uses: ./.github/workflows/workflow-oracle-docker.yml
    with:
      tasks:
        - Test Task 1
        - Test Task 2
