name: Use Oracle Service

on:
  push:
    branches: [ "main" ]
jobs:
  use-oracle-service:
    id: oracle-service
    uses: ./.github/workflows/workflow-oracle-docker.yml
    with:
      tasks: 12345678
  job1:
    steps:
      - name: step1
        run: |
          echo ${{steps.oracle-service.outputs.ip}}
          echo ${{steps.oracle-service.outputs.port}}
