name: GitHub Actions Demo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  job1:
    name: this is job1
    runs-on: ubuntu-latest
    steps:
      - name: run oracle container
        run: |
           echo ignore docker start
           docker run -d --name oracle19c -p 1521:1521 \
           -e ORACLE_SID=ORCL -e ORACLE_PDB=ORCLPDB1 -e ORACLE_PWD=Oracle123 \
           -e ORACLE_EDITION=standard -e ORACLE_CHARACTERSET=AL32UTF8 \
           registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c
           docker exec -it oracle19c sqlplus / as sysdba
           ALTER PLUGGABLE DATABASE ORCLPDB1 OPEN;
           ALTER USER system IDENTIFIED BY Oracle123;
  job2:
    name: this is job2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Download and Install Oracle JDBC Driver
        run: |
          wget https://download.oracle.com/otn-pub/otn_software/jdbc/236/ojdbc8.jar
          mvn install:install-file \
          -DgroupId=com.oracle \
          -DartifactId=ojdbc8 \
          -Dversion=19.3.0.0 \
          -Dpackaging=jar \
          -Dfile=ojdbc8.jar
        shell: bash
  job3:
    name: this is job3
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: |
          echo connect oracle.
          docker exec -it oracle19c  sqlplus system/Oracle123@localhost:1521/ORCLPDB1
          select count(1) from all_tables;
