# Workflow: workflow demo 入口程序
name: Macos-Oracle Demo
on:
  push:
    branches: [ "main" ]

jobs:
  oracle-db:
    runs-on: macos-latest
    steps:
      - name: 启用 Rosetta 并启动 Colima
        run: |
          brew update 
          brew install colima docker qemu
          colima start --arch x86_64 --vm-type=vz --vz-rosetta --mount-type=virtiofs --memory 4

        shell: bash
      - name: 设置 Docker 缓存
        uses: actions/cache@v3
        with:
          path: /tmp/docker-images
          key: oracle-docker-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            oracle-docker-${{ runner.os }}-

      - name: 预拉取 Oracle 镜像
        run: |
          docker pull container-registry.oracle.com/database/free:23.5.0.0-lite

      - name: 启动 Oracle 容器（限制 CPU & 内存）
        run: |
          docker run --platform linux/amd64 -d --name oracle23 \
            --cpus=1 -m=3g \
            -p 1521:1521 -p 5500:5500 \
            -e ORACLE_PDB=ORCLPDB \
            -e ORACLE_PWD=Oracle123 \
            -e DB_MEMORY=2g \
            container-registry.oracle.com/database/free:23.5.0.0-lite

      - name: Verify Oracle Database is running
        id: oracleContainer
        shell: bash
        run: |
            docker ps
            sleep 10
            while true; do
              log_output=$(docker logs oracle23 2>&1 | grep -i "DATABASE IS READY TO USE" || true)
              if [ -z "$log_output" ]; then
                echo "oracle service not started, retry in 10 seconds..."
                docker logs --tail 10 oracle23
                sleep 30
              else
                echo "oracle service started."
                break
              fi
            done
