name: GitHub Actions Demo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  job4:
    name: this is job4
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker images
        uses: actions/cache@v3
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-image-${{ hashFiles('**/Dockerfile', '**/*.sh') }}
          restore-keys: |
            ${{ runner.os }}-docker-image-
      - name: Pull Docker image
        run: |
          docker pull registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c
