name: Oracle Demo
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    name: start oracle container
    runs-on: ubuntu-latest
    services:
      # Oracle service (label used to access the service container)
      oracle:
        # Docker Hub image (feel free to change the tag "latest" to any other available one)
        image: gvenzl/oracle-free:latest
        # Provide passwords and other environment variables to container
        env:
          ORACLE_PASSWORD: Oracle123
        # Forward Oracle port
        ports:
          - 1521:1521
        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install libaio1 (required for Oracle Instant Client)
        run: |
          sudo apt-get update
          wget http://archive.ubuntu.com/ubuntu/pool/main/liba/libaio/libaio1_0.3.112-5_amd64.deb
          sudo dpkg -i libaio1_0.3.112-5_amd64.deb

      - name: Set up Oracle Instant Client
        run: |
          wget https://download.oracle.com/otn_software/linux/instantclient/2360000/instantclient-basic-linux.x64-23.6.0.24.10.zip
          wget https://download.oracle.com/otn_software/linux/instantclient/2360000/instantclient-sqlplus-linux.x64-23.6.0.24.10.zip

          mkdir -p /opt/oracle/instantclient-basic
          mkdir -p /opt/oracle/instantclient-sqlplus
          unzip -q instantclient-basic-linux.x64-23.6.0.24.10.zip -d /opt/oracle/instantclient-basic
          unzip -q instantclient-sqlplus-linux.x64-23.6.0.24.10.zip -d /opt/oracle/instantclient-sqlplus
          
          cp -rf /opt/oracle/instantclient-sqlplus/instantclient_23_6/* /opt/oracle/instantclient-basic/instantclient_23_6/
          
          ls /opt/oracle/instantclient-basic
          ls /opt/oracle/instantclient-sqlplus

      - name: Set up environment variables
        run: |
          echo "export PATH=/opt/oracle/instantclient-basic/instantclient_23_6:$PATH" >> $GITHUB_ENV
          echo "export LD_LIBRARY_PATH=/opt/oracle/instantclient-basic/instantclient_23_6:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "export TNS_ADMIN=/opt/oracle/instantclient-basic/instantclient_23_6" >> $GITHUB_ENV

      - name: Verify sqlplus
        run: |
          sqlplus -v


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Oracle pytest

      - name: Wait for Oracle DB to be ready
        run: |
          until echo "SELECT 1 FROM DUAL;" | sqlplus -S system/Oracle123@localhost:1521/FREEPDB1; do
            echo "Waiting for Oracle DB to be ready..."
            sleep 2
          done

      - name: Run tests
        run: |
          # Run your tests that interact with Oracle DB
          pytest tests/
