name: Oracle Demo
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    name: start oracle container
    runs-on: ubuntu-latest
    services:
      # Oracle service (label used to access the service container)
      oracle:
        # Docker Hub image (feel free to change the tag "latest" to any other available one)
        image: gvenzl/oracle-free:latest
        # Provide passwords and other environment variables to container
        env:
          ORACLE_PASSWORD: Oracle123
        # Forward Oracle port
        ports:
          - 1521:1521
        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install libaio1 manually
        run: |
          # Download libaio1 .deb package from Ubuntu archive
          wget http://archive.ubuntu.com/ubuntu/pool/main/liba/libaio/libaio1_0.3.112-5_amd64.deb
          
          # Install the downloaded package
          sudo dpkg -i libaio1_0.3.112-5_amd64.deb
          
          # Ensure there are no unmet dependencies
          sudo apt-get install -f

      - name: Install Oracle Instant Client
        run: |
          # Install necessary dependencies
          sudo apt-get update
          #sudo apt-get install -y libaio1

          # Download and install Oracle Instant Client
          wget https://download.oracle.com/otn_software/linux/instantclient/215000/oracle-instantclient-basic-linuxx64-21.5.0.0.0.zip
          unzip oracle-instantclient-basic-linuxx64-21.5.0.0.0.zip
          sudo mv instantclient_21_5 /opt/oracle/
          sudo ln -s /opt/oracle/instantclient_21_5 /opt/oracle/instantclient
          sudo ln -s /opt/oracle/instantclient/sqlplus /usr/local/bin/sqlplus

      - name: Verify sqlplus installation
        run: sqlplus -version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Oracle pytest

      - name: Wait for Oracle DB to be ready
        run: |
          echo ${LD_LIBRARY_PATH}
          until echo "SELECT 1 FROM DUAL;" | sqlplus -S system/Oracle123@localhost:1521/FREEPDB1; do
            echo "Waiting for Oracle DB to be ready..."
            sleep 2
          done

      - name: Run tests
        run: |
          # Run your tests that interact with Oracle DB
          pytest tests/
