name: Oracle Demo
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    name: start oracle container
    runs-on: ubuntu-latest
    services:
      # Oracle service (label used to access the service container)
      oracle:
        # Docker Hub image (feel free to change the tag "latest" to any other available one)
        image: gvenzl/oracle-free:latest
        # Provide passwords and other environment variables to container
        env:
          ORACLE_PASSWORD: Oracle123
        # Forward Oracle port
        ports:
          - 1521:1521
        # Provide healthcheck script options for startup
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libaio1

      - name: Download Oracle Instant Client
        run: |
          curl -LO https://download.oracle.com/otn_software/linux/instantclient/213000/instantclient-basic-linux.x64-21.3.0.0.0.zip
          curl -LO https://download.oracle.com/otn_software/linux/instantclient/213000/instantclient-sqlplus-linux.x64-21.3.0.0.0.zip

      - name: Unzip Oracle Instant Client
        run: |
          sudo apt-get install -y unzip
          unzip instantclient-basic-linux.x64-21.3.0.0.0.zip -d /opt/oracle
          unzip instantclient-sqlplus-linux.x64-21.3.0.0.0.zip -d /opt/oracle

      - name: Set up environment variables
        run: |
          echo "export PATH=/opt/oracle/instantclient_21_3:$PATH" >> $GITHUB_ENV
          echo "export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_3:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Verify sqlplus is available
        run: |
          sqlplus -v
