name: Actions Cache Demo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  job1:
    name: this is job1
    runs-on: ubuntu-latest
    steps:
      - name: Restore oracle Cache
        id: restore
        uses: actions/cache/restore@v3
        with:
          path: ~/.docker
          key: Linux-docker-image-oracle19c
      - name: Pull Docker image
        run: |
          docker pull registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c
          echo run
      - name: Save oracle Cache
        if: steps.restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/.docker
          key: Linux-docker-image-oracle19c

