# Workflow: workflow demo 入口程序
name: Windows-Oracle Demo
on:
  push:
    branches: [ "main" ]

jobs:
  oracle-db:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Executable Permission for Script
        run: chmod +x .github/scripts/oracle.sh

      - uses: vedantmgoyal9/setup-wsl2@main

      - name: Install Docker
        shell: wsl-run {0}
        run: |
          sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          sudo apt update
          sudo apt install docker-ce docker-ce-cli containerd.io -y
          sudo service docker start
          docker --version
          docker pull container-registry.oracle.com/database/free:23.5.0.0-lite

      - name: 启动 Oracle 容器（限制 CPU & 内存）
        shell: wsl-run {0}
        run: |
          docker run -d --name oracle23-1521 \
            -p 1521:1521 -p 5501:5500 \
            -e ORACLE_PDB=ORCLPDB \
            -e ORACLE_PWD=Oracle123 \
            -e DB_MEMORY=1.5g \
            container-registry.oracle.com/database/free:23.5.0.0-lite

      - name: Verify Oracle Database is running
        id: oracleContainer
        shell: wsl-run {0}
        run: |
          for port in oracle23-1521; do
            while true; do
            log_output=$(docker logs $port 2>&1 | grep -i "DATABASE IS READY TO USE" || true)
            if [ -z "$log_output" ]; then
             echo "oracle service not started, retry in 10 seconds..."
             docker logs --tail 10 $port
             sleep 10
            else
             echo "oracle service started."
             break
            fi
            done
          done

      - name: Run Password Update Script
        shell: bash
        run: .github/scripts/oracle.sh 1521 Oracle123
          
