name: GitHub Actions Demo
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    name: this is job1
    runs-on: windows-latest
    steps:
#      - name: Set up Docker
#        uses: docker/setup-docker-action@v4
#
#      - name: Run Docker command
#        run: docker --version
      - name: Start Oracle container
        run: |
          $values = "1521", "1522"
          foreach ($P in $values) {
           Write-Host "Processing value $P"
          }
        shell: pwsh
