# Workflow: workflow demo 入口程序
name: GitHub Actions Demo
on:
  push:
    branches: [ "main" ]

jobs:
  use-oracle-service:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: windows docker
        uses: ./.github/actions/windows
        with:
          ports: 1521 1522 1523
