name: GitHub Actions Demo
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    name: this is job1
    runs-on: windows-latest
    steps:
#      - name: Set up Docker
#        uses: docker/setup-docker-action@v4
#
#      - name: Run Docker command
#        run: docker --version
      - name: Start Oracle container
        shell: cmd
        run: |
          for /L %%P in (1521,1522) do
          echo %%P
