name: Windows Demo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  job1:
    name: this is job1
    runs-on: windows-latest
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

#      - name: Set up Docker
#        uses: cpunion/setup-docker@v1
      - name: docker install
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe -OutFile DockerInstaller.exe
          Start-Process -Wait -FilePath .\DockerInstaller.exe -ArgumentList "install --quiet"
          Remove-Item -Force DockerInstaller.exe
          # Add Docker to PATH
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")
          docker --version
      - name: Run Docker commands
        run: |
          where docker
          docker --version
          docker info