name: Actions Cache Demo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  job1:
    name: this is job1
    runs-on: ubuntu-latest
    steps:
      - name: Restore oracle Cache
        id: restore
        uses: actions/cache/restore@v3
        with:
          path: ~/.docker
          key: Linux-docker-image-oracle19c
      - name: Pull Docker image
        run: |
          docker pull registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c
      - name: Save oracle Cache
        #if: steps.restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ~/.docker
          key: Linux-docker-image-oracle19c
      - name: run oracle container
        run: |
          docker run -d --name oracle19c -p 1521:1521 \
          -e ORACLE_SID=ORCL -e ORACLE_PDB=ORCLPDB1 -e ORACLE_PWD=Oracle123 \
          -e ORACLE_EDITION=standard -e ORACLE_CHARACTERSET=AL32UTF8 \
          registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c
      - name: Verify DM Database is running
        shell: bash
        run: |
          while true
          do
            log_output=$(docker logs oracle19c 2>&1 | grep -i "XDB initialized.")
            if [ -z "$log_output" ]; then
              echo "'complete' not found in the logs, retrying in 10 seconds..."
              sleep 10
            else
              echo "'XDB initialized.' found in the logs, continuing."
              break
            fi
          done

